version: "3"

services:
  app:
    build: ./app
    environment:
      - BOT_TOKEN=7053310527:AAExrwk4_GnHtRlN1uDGuiQsZdoNvF2K7zc
      - ENV=development
      - REDIS_ADDRESS=redis:6379
      - REDIS_DB=0
    depends_on:
      - redis
  redis:
    image: redis/redis-stack-server
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data:
