version: "3"

services:
  dev-app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment:
      - BOT_TOKEN=$TELEGRAM_BOT_API_KEY
      - ENV=local
      - REDIS_ADDRESS=redis:6379
      - REDIS_DB=0
    volumes:
      - "./app:/app"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  redis-data:
